### ISSUE TITLE
How to get this dataset?

### ISSUE THREAD

**Issue by ErvinXie** [akratiiet/RaboBank_Dataset#1]
Hello, how should i get this dataset?

**Comment by akratiiet** [comment]
Please email to a.saxena@liacs.leidenuniv.nl

**Comment by ErvinXie** [comment]
hello, i have emailed to you last week, did you received my email? If you cannot find it, please contact me at xwy21@mails.tsinghua.edu.cn . Thank you very much!

**Comment by ErvinXie** [comment]
> Please email to [a.saxena@liacs.leidenuniv.nl](mailto:a.saxena@liacs.leidenuniv.nl)

Hello, I emailed  to you again a few days earlier, did you receive it?
